baseurl = "https://powerhousegen.com/"
title = "Powerhouse Generators"
theme = "hugo-universal-theme"
themesDir = "themes"
languageCode = "en-us"
publishDir = "docs"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-128625038-2"

# Define the number of posts per page
paginate = 10

[menu]

# Main menu

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1
    
[[menu.main]]
    name = "Testimonials"
    url  = "/#testimonials"
    weight = 2

#[[menu.main]]
 #  name = "FAQ"
  #  identifier = "faq"
   # url  = "/faq/"
    #weight = 3

[[menu.main]]
    name = "Contact"
    url  = "/contact/"
    weight = 4
    
# Top bar social links menu

[[menu.topbar]]
    weight = 4
    name = "Email"
    url = "mailto:info@powerhousegen.com"
    pre = "<i class='fa fa-2x fa-envelope'></i>"

[params]
    title = "Powerhouse Generators"
    viewMorePostLink = "/blog/"
    author = "Mitch Mountney"
    defaultKeywords = ["generators", "powerhouse generators", "generator installation"]
    defaultDescription = "Powerhouse Generators"

    # Google Maps API key (if not set will default to not passing a key.)
    googleMapsApiKey = "AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "info@powerhousegen.com"

    about_us = "We offer over 30 years of experience in the electrical industry. We take on a wide range of generator installations and repairs and a variety of other jobs. We are committed to providing a personalized service for each individual project we take on and look forward to building strong, long-term relationships with our clients while guaranteeing your satisfaction."
    copyright = "Copyright &copy; 2021 Powerhouse Generators | All rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/logo_400px.jpg"
    address = """<p><strong>Powerhouse Generators</strong>
        <br><a href="tel:248-961-3647">248-961-3647</a>
        <br><a href="mailto:info@powerhousegen.com">info@powerhousegen.com</a>
      </p>
      """
    phone = "248-961-3647"

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">Contact us today! <a href="tel:248-961-3647">248-961-3647</a>.</p>
      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fa fa-phone"></i></a>
      <a href="#" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = true
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.
    featureinfo = """<h2 align="center" style="font-weight:300;">See why our customers give <span style="font-weight: 700;">Powerhouse Generators</span> 5 stars!</h2><h2 align="center">Call for your free quote today: <a href="tel:239-235-8078">239-235-8078</a></h2>"""

[params.testimonials]
    enable = true
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Testimonials"
    subtitle = "We have worked with a number of clients, and we are always excited to see the great things they have to say about Powerhouse Generators."

[params.see_more]
    enable = false
    icon = "fa fa-file-code-o"
    title = "Do you want to see more?"
    subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
    link_url = "#"
    link_text = "Check other homepages"

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Our Brands"
    subtitle = ""

[params.recent_posts]
    enable = false
    title = "From our blog"
    subtitle = "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo."
